
---
- hosts: localhost
  gather_facts: true
  vars:
    config: '{{  ovconfig_file }}'

  tasks:
     
    - name: Gather facts about all Enclosures
      hpe.oneview.oneview_enclosure_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=enclosures
