
---
- hosts: localhost
  gather_facts: true

  tasks:
     
    - name: Gather facts about all Enclosures
      hpe.oneview.oneview_enclosure_facts:
        config: {{ ovconfig_file }}
      delegate_to: localhost

    - debug: var=enclosures